#  Created byMartin.cz
#  Copyright (c) Martin Strohalm. All rights reserved.

# import modules
import wx

ID_QUIT = wx.ID_EXIT

ID_VIEW_COLLECTIONS = wx.NewIdRef()
ID_VIEW_PDF = wx.NewIdRef()
ID_VIEW_DETAILS = wx.NewIdRef()

ID_LIBRARY_NEW = wx.NewIdRef()
ID_LIBRARY_OPEN = wx.NewIdRef()

ID_ARTICLES_SEARCH = wx.NewIdRef()
ID_ARTICLES_OPEN_PDF = wx.NewIdRef()
ID_ARTICLES_OPEN_DOI = wx.NewIdRef()
ID_ARTICLES_OPEN_PMID = wx.NewIdRef()
ID_ARTICLES_REVEAL_PDF = wx.NewIdRef()
ID_ARTICLES_COPY_CITATION = wx.NewIdRef()
ID_ARTICLES_COPY_SUMMARY = wx.NewIdRef()
ID_ARTICLES_COPY_LINK = wx.NewIdRef()
ID_ARTICLES_NEW = wx.NewIdRef()
ID_ARTICLES_IMPORT = wx.NewIdRef()
ID_ARTICLES_EDIT = wx.NewIdRef()
ID_ARTICLES_DELETE = wx.NewIdRef()
ID_ARTICLES_TRASH = wx.NewIdRef()
ID_ARTICLES_TRASH_MENU = wx.NewIdRef()
ID_ARTICLES_RESTORE = wx.NewIdRef()
ID_ARTICLES_LABELS = wx.NewIdRef()
ID_ARTICLES_MATCH = wx.NewIdRef()
ID_ARTICLES_UPDATE = wx.NewIdRef()
ID_ARTICLES_ATTACH_PDF = wx.NewIdRef()
ID_ARTICLES_COLLECTIONS = wx.NewIdRef()

ID_REPOSITORY_SEARCH = wx.NewIdRef()
ID_REPOSITORY_RECENT = wx.NewIdRef()
ID_REPOSITORY_RECENT_FIRST_AUTHOR = wx.NewIdRef()
ID_REPOSITORY_RECENT_LAST_AUTHOR = wx.NewIdRef()
ID_REPOSITORY_RECENT_JOURNAL = wx.NewIdRef()

ID_ARTICLES_RATING = wx.NewIdRef()
ID_ARTICLES_RATING_0 = wx.NewIdRef()
ID_ARTICLES_RATING_1 = wx.NewIdRef()
ID_ARTICLES_RATING_2 = wx.NewIdRef()
ID_ARTICLES_RATING_3 = wx.NewIdRef()
ID_ARTICLES_RATING_4 = wx.NewIdRef()
ID_ARTICLES_RATING_5 = wx.NewIdRef()

ID_ARTICLES_COLOUR = wx.NewIdRef()
ID_ARTICLES_COLOUR_RED = wx.NewIdRef()
ID_ARTICLES_COLOUR_ORANGE = wx.NewIdRef()
ID_ARTICLES_COLOUR_YELLOW = wx.NewIdRef()
ID_ARTICLES_COLOUR_GREEN = wx.NewIdRef()
ID_ARTICLES_COLOUR_BLUE = wx.NewIdRef()
ID_ARTICLES_COLOUR_PURPLE = wx.NewIdRef()
ID_ARTICLES_COLOUR_GRAY = wx.NewIdRef()

ID_COLLECTIONS_NEW_MANUAL = wx.NewIdRef()
ID_COLLECTIONS_NEW_SMART = wx.NewIdRef()
ID_COLLECTIONS_NEW_FROM_SELECTION = wx.NewIdRef()
ID_COLLECTIONS_EDIT = wx.NewIdRef()
ID_COLLECTIONS_DELETE = wx.NewIdRef()
ID_COLLECTIONS_EMPTY_TRASH = wx.NewIdRef()

ID_LABELS_NEW = wx.NewIdRef()
ID_LABELS_EDIT = wx.NewIdRef()
ID_LABELS_DELETE = wx.NewIdRef()
